version: '3'
services:
  php:
    container_name: php8
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - '.:/var/www/html'
    depends_on:
      - es01
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
  es01:
    image: elasticsearch:7.10.1
    container_name: es01
    environment:
      - network.host=0.0.0.0
      - node.name=es01
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  kibana:
    image: kibana:7.10.1
    container_name: kibana
    environment:
      - server.host=0.0.0.0
    links:
      - es01:elasticsearch
    ports:
      - 5601:5601
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: sample
      MYSQL_USER: sample
      MYSQL_PASSWORD: secret
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/mysql.conf.d/z.cnf
